{{- if .Values.persistence.enabled }}
{{- if (not .Values.persistence.appData.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "navidrome.fullname" . }}-data
spec:
  accessModes:
    - {{ .Values.persistence.appData.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.appData.pvcSize | quote }}
  storageClassName: {{ .Values.persistence.appData.storageClassName }}
{{- end }}

---

{{- if (not .Values.persistence.music.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "music-storage"
spec:
  accessModes:
    - {{ .Values.persistence.music.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.music.pvcSize | quote }}
  storageClassName: {{ .Values.persistence.music.storageClassName }}
{{- end }}
{{- end}}